version: 2
workflow:
  mode: active
overrides:
  "package/pypi/beautifulsoup4":
    - path: source_url
      value: "https://git.launchpad.net/beautifulsoup"
      reason: "PyPI metadata points to non-git URL (crummy.com), actual source is on Launchpad"
